[project]
name = "asteroids-game"
version = "0.1.0"
description = "Simple game about shooting at asteroids"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jq>=1.11.0",
    "pygame==2.6.1",
]
